version: "3.7"

services:
  postgres:
    image: postgis/postgis
    env_file: .env
    restart: always
    ports:
      - "5434:5432"
    volumes:
      - ./.postgres:/var/lib/postgresql/data

  django:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    depends_on:
      - postgres
    env_file: .env
    restart: always
    volumes:
      - ./:/JUDA/
   # ports:
   #   - "8000:8000"
    expose:
      - 8000

  nginx:
    image: nginx:latest
    restart: always
    depends_on:
      - django
    ports:
      - "80:80"
    volumes:
      - ./nginx/dev:/etc/nginx/conf.d/:ro