version: "3.10"

services:
  postgres:
    image: postgres:15
    env_file: .env
    restart: always
    ports:
      - "5434:5432"
    volumes:
      - ./.postgres:/var/lib/postgresql/data

  django:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    depends_on:
      - postgres
    env_file: .env
    volumes:
      - ./:/JUDA/
    ports:
      - "8000:8000"