# Generated by Django 4.2 on 2023-11-10 14:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('commune', '0001_initial'),
        ('neighborhood', '0001_initial'),
        ('leader', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Voter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre')),
                ('lastname', models.CharField(max_length=100, verbose_name='Apellido')),
                ('type_of_document', models.CharField(choices=[('cedula de ciudadania', 'Cedula de ciudadania'), ('cedula extranjeria', 'Cedula extranjeria')], max_length=100, verbose_name='Tipo de documento')),
                ('document_number', models.CharField(max_length=100, verbose_name='Numero de documento')),
                ('email', models.EmailField(max_length=254, verbose_name='Correo electronico')),
                ('phone', models.CharField(max_length=100, verbose_name='Celular')),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('voting_booth', models.CharField(blank=True, max_length=500, null=True, verbose_name='Puesto de votacion')),
                ('name_commune', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='commune.commune', verbose_name='Comuna')),
                ('name_leader', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='leader.leader', verbose_name='Lider')),
                ('name_neighborhood', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='neighborhood.neighborhood', verbose_name='Barrio')),
            ],
        ),
    ]
