# Generated by Django 4.2 on 2023-11-10 14:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('neighborhood', '0001_initial'),
        ('commune', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Leader',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre')),
                ('lastname', models.CharField(max_length=100, verbose_name='Apellido')),
                ('type_of_document', models.CharField(choices=[('cedula de ciudadania', 'Cedula de ciudadania'), ('cedula extrangera', 'Cedula extrenagera')], max_length=100, verbose_name='Tipo de documento')),
                ('document_number', models.CharField(max_length=100, verbose_name='Numero de documento')),
                ('email', models.EmailField(max_length=254, verbose_name='Correo electronico')),
                ('address_of_residence', models.CharField(max_length=100, verbose_name='Direccion de residencia')),
                ('phone', models.CharField(max_length=100, verbose_name='Celular')),
                ('commune_neighborhood', models.CharField(choices=[('barrio', 'Barrio'), ('comuna', 'Comuna')], max_length=100, verbose_name='comuna o barrio')),
                ('name_commune', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='commune.commune', verbose_name='Nombre de la comuna')),
                ('name_neighborhood', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='neighborhood.neighborhood', verbose_name='Nombre del barrio')),
            ],
        ),
    ]
