# Generated by Django 4.2 on 2023-11-10 14:16

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre')),
                ('last_name', models.CharField(max_length=100, verbose_name='Apellido')),
                ('type_of_document', models.CharField(choices=[('cedula de ciudadania', 'Cedula de ciudadania'), ('cedula extrangera', 'Cedula extrenagera')], max_length=100, verbose_name='Tipo de documento')),
                ('document_number', models.CharField(max_length=100, verbose_name='Numero de documento')),
                ('email', models.EmailField(max_length=254, verbose_name='Correo electronico')),
                ('address_of_residence', models.CharField(max_length=100, verbose_name='Direccion de residencia')),
                ('phone', models.CharField(max_length=13, verbose_name='Celular')),
                ('political_party', models.FileField(blank=True, null=True, upload_to='imaproduct', validators=[django.core.validators.FileExtensionValidator(['svg', 'png', 'jpg', 'jpeg'])], verbose_name='Imagen del prodcuto')),
                ('Desired_position', models.CharField(max_length=50, verbose_name='Cargo deseado')),
            ],
        ),
    ]
